HTML to dom
WorldBrain/Research-Engine pull request #15
Opened 2016-10-28 17:42 UTC by oliversauter

i made some changes, now at least we have the url_html parsed into a real DOM tree. this should help.

2016-10-28 18:18 UTC, bohrium272 requested changes
Please change the loop statement at line 372 to `(0, history.length)`

2016-10-29 08:39 UTC, oliversauter commented
oh yes! had that for experimental purposes. Thanks for correcting. Fixed!

2016-10-30 21:52 UTC, obsidianart commented on extension/js/download_History.js
> +                document.getElementById('abort_button').remove()
to do it properly you need to remove the click event first or you will create memory leak

2016-10-30 21:54 UTC, obsidianart commented on extension/js/background.js
> +        console.log(data.text)
needed?

2016-10-30 21:55 UTC, obsidianart commented on extension/js/download_History.js
> +var abort_status = 0
if is only 0 or 1 better to say isAbortedByUser = false

2016-10-30 21:57 UTC, obsidianart commented on extension/assets/download_history.html
> +<button id="abort_button" style="float:right" class="ui red button">Cancel Download</button>
I would say this stop downloading, doesn't cancel it as you are saving what you downloading till that point

2016-10-30 21:58 UTC, obsidianart commented on extension/js/background.js
>          timeIndex.push(time.toString());
I don't see the point of changing time toString(), numbers are as good (maybe there's a reason I can't understand)

2016-10-30 21:59 UTC, obsidianart commented on extension/js/download_History.js
> +                console.log("Cancelled Download")
"Downloaded cancelled" (but I would say is stopped not cancelled)

2016-10-30 22:00 UTC, obsidianart commented on extension/js/download_History.js
> +                        divs = body_text.getElementsByTagName('div')
are you assuming the content is inside div? what about article, section, main and so on?

2016-10-30 22:01 UTC, obsidianart commented on extension/js/download_History.js
> +                        divs = body_text.getElementsByTagName('div')
We should go in this direction or find an open version of this https://www.readability.com/developers/api/parser

2016-10-31 05:38 UTC, bohrium272 approved these changes

2016-10-31 07:42 UTC, oliversauter commented on extension/js/download_History.js
> +var abort_status = 0
done.

2016-10-31 07:42 UTC, oliversauter commented on extension/js/download_History.js
> +                document.getElementById('abort_button').remove()
I don't understand that one.

2016-10-31 07:42 UTC, oliversauter commented on extension/js/download_History.js
> +                console.log("Cancelled Download")
Done

2016-10-31 07:44 UTC, oliversauter commented on extension/js/download_History.js
> +                        divs = body_text.getElementsByTagName('div')
Actually we use readablity already for parsing the article before saving it. Will test out if we can use the local version we have. 

@arpitgogia said it only return parts of the text but that was before the adjustments to the correct DOM tree of the HTML file.

2016-10-31 07:45 UTC, oliversauter commented on extension/js/background.js
> +        console.log(data.text)
removed

2016-10-31 07:45 UTC, obsidianart commented on extension/js/download_History.js
> +                document.getElementById('abort_button').remove()
at line 8 you have
```
document.getElementById('abort_button').onclick = function(){
    abort_status = 1
};
```
which look like a bind but I just realized is not (never saw this tecnique before), you can just ignore this comment

2016-10-31 07:45 UTC, oliversauter commented on extension/assets/download_history.html
> +<button id="abort_button" style="float:right" class="ui red button">Cancel Download</button>
legacy piece. Forgot to remove it. was before I added the cancel button. Thanks!

2016-11-07 11:10 UTC, oliversauter commented on extension/js/download_History.js
> +                        divs = body_text.getElementsByTagName('div')
readabilities library is also not ideal. The browser itself with document.body.textContent is the best way to retrieve the content.

I have not found a way to extract just the visible textual content from an article with a JS library.

2016-11-15 20:00 UTC, oliversauter commented
closing as being obsolete with #27

2016-11-15 20:00 UTC, closed without merging